name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.0'
        bundler-cache: true
    
    - name: Update bundle platforms
      run: |
        bundle lock --add-platform x86_64-linux
        bundle lock --add-platform ruby
        bundle lock --add-platform x64-mingw-ucrt
    
    - name: Install dependencies
      run: |
        bundle config set --local path 'vendor/bundle'
        bundle install
    
    - name: Run tests
      run: bundle exec rspec

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | sh
    
    - name: Deploy to Railway
      run: |
        railway up --service ${{ secrets.RAILWAY_SERVICE_NAME }}
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }} 